name: Deploy to WP Engine
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to WPE
        uses: wpengine/github-action-wpe-site-deploy@v3
        with:
          WPE_SSHG_KEY_PRIVATE: ${{ secrets.WPE_SSHG_KEY_PRIVATE }}
          WPE_ENV: wpurvenueweb
          SRC_PATH: "."
          REMOTE_PATH: "wp-content/plugins/wp-urvenue-webservices/"
          PHP_LINT: false
          CACHE_CLEAR: true
          FLAGS: -azvr --no-times --no-perms